// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShopping_API.DataStore;

#nullable disable

namespace OnlineShopping_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230617170633_SeedCategoryTable")]
    partial class SeedCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineShopping.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "",
                            Name = "Mobiles"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "",
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "",
                            Name = "Stationery"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
